### ISSUE TITLE
ユビキタスロボティクス issue書き込み練習

### ISSUE THREAD

**Issue by n-ando** [sealbreeder/TMU-Ubiquitous-Robotics#2]
ユビキタスロボティクス issue書き込み練習です。
受講している人はここに、「gitのいインストールとアカウント作成まで終わりました」と書き込んで下さい。

**Comment by TomokiKomiya** [comment]
gitのいインストールとアカウント作成まで終わりました

**Comment by kaineigi** [comment]
gitのいインストールとアカウント作成まで終わりました

**Comment by cactusHats** [comment]
インストールとアカウント作成まで完了いました．

**Comment by lina1280187381** [comment]
インストールとアカウント作成まで終わりました

**Comment by Kurokawaharuka** [comment]
gitのいインストールとアカウント作成まで終わりました

**Comment by shanewestlife** [comment]
gitのいインストールとアカウント作成まで終わりました

**Comment by KKDWB** [comment]
gitのいインストールとアカウント作成まで終わりました

**Comment by labiybafakh** [comment]
インストールとアカウント作成まで完了いました．

**Comment by tanayahikaru** [comment]
インストールとアカウント作成まで完了しました

**Comment by n-ando** [comment]
クローズします。
